import "../app/globals.css";
import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
 
const inter = Red_Hat_Display({ subsets: ["latin"] });
import Header from "../components/common/header";
import HomeFooter from "@/components/home/homeFooter";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <div>{children}</div>
        {/* <HomeFooter/> */}
      </body>
    </html>
  );
}
